version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo "No build script defined"
artifacts:
  files:
    - '**/*'
